# Site settings
title: Portfolio
description: Hi! This is JA's PortfolioğŸ’»
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Lee JeongA
user_description: ì•ˆë…•í•˜ì„¸ìš”ğŸ‘‹ ë°±ì—”ë“œ ê°œë°œì„ ê³µë¶€í•˜ê³  ìˆìŠµë‹ˆë‹¤!<br>Python ê¸°ë°˜ì˜ Flask, Django, DRFë¥¼ ì´ìš©í•œ ML ì›¹í˜ì´ì§€ ì œì‘ í”„ë¡œì íŠ¸ë¥¼ ì£¼ë¡œ ì§„í–‰í–ˆìŠµë‹ˆë‹¤. í”„ë¡œì íŠ¸ëŠ” ë°±ì—”ë“œì™€ í”„ë¡ íŠ¸ì—”ë“œë¥¼ ê°€ë¦¬ì§€ ì•Šê³  í–ˆìŠµë‹ˆë‹¤.<br>Python ì´ì™¸ì—ë„ JAVA ë“±ì„ ì´ìš©í•œ í”„ë¡œì íŠ¸ì™€ ë„¤ì´í‹°ë¸Œ ì•± ì œì‘ë„ ê°€ëŠ¥í•©ë‹ˆë‹¤.
user_title: Backend Developer
email: zeonga1102@gmail.com
twitter_username: lorem_ipsum
github_username:  zeonga1102
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
